# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opponents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='whole_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
