# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opponents', '0002_player_whole_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='sport',
        ),
        migrations.AddField(
            model_name='player',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opponents.Sport'),
        ),
    ]
