# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opponents', '0004_auto_20160116_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='sport',
        ),
        migrations.AddField(
            model_name='sport',
            name='player',
            field=models.ManyToManyField(to='opponents.Player'),
        ),
    ]
