# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opponents', '0005_auto_20160116_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='player',
        ),
        migrations.AddField(
            model_name='sport',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opponents.Player'),
        ),
    ]
