# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opponents', '0006_auto_20160116_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='player',
        ),
        migrations.AddField(
            model_name='player',
            name='sport',
            field=models.ManyToManyField(null=True, to='opponents.Sport'),
        ),
    ]
