# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opponents', '0008_auto_20160116_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='sports',
            field=models.ManyToManyField(to='opponents.Sport'),
        ),
    ]
