# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opponents', '0009_auto_20160116_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='sports',
        ),
        migrations.AddField(
            model_name='player',
            name='sports',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opponents.Sport'),
        ),
    ]
