# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opponents', '0010_auto_20160116_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='sports',
        ),
        migrations.AddField(
            model_name='player',
            name='sports',
            field=models.ManyToManyField(to='opponents.Sport'),
        ),
    ]
