# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opponents', '0011_auto_20160116_1217'),
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='SportMember',
    #         fields=[
    #             ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #         ],
    #     ),
    #     migrations.AlterField(
    #         model_name='player',
    #         name='sports',
    #         field=models.ManyToManyField(through='opponents.SportMember', to='opponents.Sport'),
    #     ),
    #     migrations.AddField(
    #         model_name='sportmember',
    #         name='player',
    #         field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opponents.Player'),
    #     ),
    #     migrations.AddField(
    #         model_name='sportmember',
    #         name='sport',
    #         field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opponents.Sport'),
    #     ),
    # ]
