# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opponents', '0012_auto_20160116_1228'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='sportmember',
    #         name='player',
    #     ),
    #     migrations.RemoveField(
    #         model_name='sportmember',
    #         name='sport',
    #     ),
    #     migrations.AlterField(
    #         model_name='player',
    #         name='sports',
    #         field=models.ManyToManyField(to='opponents.Sport'),
    #
    #     ),
    #     migrations.DeleteModel(
    #         name='SportMember',
    #     ),
    # ]
