# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opponents', '0026_auto_20160117_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player_1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='game',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
