# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opponents', '0028_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='score_player1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='score_player2',
            field=models.IntegerField(default=0),
        ),
    ]
