# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opponents', '0030_game_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opponents.Game'),
        ),
    ]
